### ISSUE TITLE
API

### ISSUE THREAD

**Issue by rafiki270** [twof/VaporCRUDRouter#1]
Would you consider changing the API to:

```swift
try router.crud(register: User.self) { controller in
    try controller.crud(children: \.todos)
}
```
?

**Comment by twof** [comment]
I like that a lot better actually. To tell you the truth. I never liked, the spelling I picked. I'll make that change and include a fixit.

**Comment by twof** [comment]
Fixed
https://github.com/twof/VaporCRUDRouter/releases/tag/1.4.0
