### ISSUE TITLE
Children route appears as parent twice

### ISSUE THREAD

**Issue by acf** [twof/VaporCRUDRouter#12]
Hi there.  I stumbled across this project while trying to learn some Vapor :-)   I did some rails a long time ago and was trying to figure out how to make the vapor router behave the way I wanted and your project seemed like just the thing.

However....

I have two models, `Project` and `Issue`.

`Project` contains

```swift
    var issues: Children<Project, Issue> {
        return children(\.projectId)
    }
```

`Issue` contains

```swift
    var project: Parent<Issue, Project> {
          return parent(\.projectId)
    }
````

My routing file contains

```swift
    router.crud(register: Project.self) { controller in
        controller.crud(children: \.issues)
    }
```

But the generates routes appear to be

```
+--------+----------------------------+
| POST   | /project/:int/project      |
+--------+----------------------------+
| GET    | /project/:int/project/:int |
+--------+----------------------------+
| GET    | /project/:int/project      |
+--------+----------------------------+
| DELETE | /project/:int/project/:int |
+--------+----------------------------+
| PUT    | /project/:int/project/:int |
+--------+----------------------------+
```

And I can't figure out what I'm doing wrong.   Any help appreciated :-)

**Comment by acf** [comment]
ping @twof  just in case (I'm not sure who gets auto-notified on issues)

**Comment by twof** [comment]
Hi! Thanks for reporting this. I'll look into it. Which tag are you using in your Package.swift?

**Comment by acf** [comment]
Hi, great to hear back... wasn't sure if I was just doing something dumb :-)

  `from: "1.7.0"` is what I have.

**Comment by acf** [comment]
https://github.com/twof/VaporCRUDRouter/blob/master/Sources/CrudRouter/CrudChildrenController.swift#L28-L29  is as far as I got.  My swift isn't great but I sort of expected to see some reference to the child here rather than the parent twice... but that could be a total red herring. 🙈

**Comment by twof** [comment]
Alright yeah definitely a bug. I'll try and fix this this weekend.

**Comment by acf** [comment]
Thanks!  And sorry I can't be more useful with a PR.
