### ISSUE TITLE
Unique property in Model

### ISSUE THREAD

**Issue by codwam** [twof/VaporCRUDRouter#8]
`final class Account: SQLiteModel {
    var id: Int?
    
    var username: String
    var password: String
    var avatar: String?
}`

Steps:

1. I want to create a new account.
2. Add `router.crud(register: Account.self)` in `router.swift`
3. It always add successfully. 
4. But, `username` not check. I hope it is a unique property.
5. How to check it ?

**Comment by twof** [comment]
If I understand your question correctly, you want to make it so it's not possible to create more than one `Account` with the same `username`.

You can do that by making the `username` field unique during migration.

https://api.vapor.codes/fluent/latest/Fluent/Protocols/SchemaBuilder.html#/s:6Fluent13SchemaBuilderPAAE6unique2onys7KeyPathCy5ModelQzqd__G_tlF

Let me know if I've misunderstood your question :)

**Comment by codwam** [comment]
Thanks

**Comment by codwam** [comment]
And another issue.
Default error message is "UNIQUE constraint failed: Category.name"
How can I customize the error message?

**Comment by twof** [comment]
I'm not entirely sure, but this is more a Fluent question than a CRUDRouter question. I'd suggest you post your question at [the fluent repo](https://github.com/vapor/fluent) instead.

You'll also get better help if you share your code.
